### ISSUE TITLE
Double permutation?

### ISSUE THREAD

**Issue by jonkoi** [dd1github/DeepSMOTE#3]
It seems that your second reconstruction loss is between the batch of reconstructed images (from permutated embeddings) and the permutated batch of ground truth images (in the same order!). Would that make the permutation pointless?

**Comment by dd1github** [comment]
Hi, the point of permutation is for the encoder and decoder to gain
"practice" at encoding one thing and decoding another, which is different
from what a typical autoencoder does.  This }practice" is helpful in the
inference phase when an input is encoded and then changed via SMOTE such
that the decoded output is different from the encoded input.  The penalty
term itself is a regularization term meant to inject diversity into the
decoder, similar in basic operation to how KL divergence in a VAE acts as a
regularization term.

Best,
Damien

**Comment by dd1github** [comment]
Closed
