### ISSUE TITLE
generate sample

### ISSUE THREAD

**Issue by fitrialif** [dd1github/DeepSMOTE#6]
hi,
i cannot run generatesample.py 
it give error FileNotFoundError: [Errno 2] No such file or directory: '.../0_trn_img.txt' 
where i get this file or how i can convert mnist dataset to this type of file

**Comment by dd1github** [comment]
Hi, does the link to the data that was provided in the ReadMe not work?

**Comment by fitrialif** [comment]
i want to used your code for my own image dataset.
