### ISSUE TITLE
Generate 0_trn_img.zip

### ISSUE THREAD

**Issue by jgcbrouns** [dd1github/DeepSMOTE#7]
Hi. Great work!

How did you generate 0_trn_img.txt? Is this the entire MNIST?

Cheers,

JB

**Comment by dd1github** [comment]
Hi,

Thanks.  Basically, I downloaded the MNIST dataset, separated the dataset
examples into classes in a dictionary, and then randomly selected indexes
from the classes to match the intended class imbalance.

Hope that helps.

Best,
Damien
