### ISSUE TITLE
Reconstructed Results very blurry 

### ISSUE THREAD

**Issue by usama13o** [dd1github/DeepSMOTE#8]
Hi 

Thanks for adding the code for your work here. 

I tried using this approach on a custom dataset where Images have more than one channel. I trained for a while and mostly the autoencoder seems to be stuck at a point where the reconstructions are just blurred images. I am not sure if it's just a matter of more training time or data, but what I noticed is that it works well when it's just reconstructing the same image using (mse) when I add the permutation part and use combo loss with the addition of (mse2), the performance deteriorates heavily and is not able to recover. 

Could it be that this just doesn't work  with my dataset or am I missing something. 

Help is appreciated.

**Comment by dd1github** [comment]
Hi, not sure why that would happen without looking at your code more closely.  We tested our code on 3 datasets that contained 3 channels.  If you send me an email at ddablain@nd.edu, I can send you some basic code that we used for 3 channel images which you can use as a check on your code, if that helps.

**Comment by mnzhao** [comment]
Do you have any ablation study on what improvement the permutation part gives? I also have similar concern. Thank you!
