### ISSUE TITLE
Is the method of smote sampling not used in the deepsmote file? There seems to be something wrong with the blogger's code

### ISSUE THREAD

**Issue by lanlan0924** [dd1github/DeepSMOTE#9]
Is the method of smote sampling not used in the DeepSMOTE_MNIST file? There seems to be something wrong with the blogger's code

**Comment by mnzhao** [comment]
If I was correct, they used SMOTE sampling when generating samples. Somewhat similar to SMOTE in hidden space. You can refer to G_SM function in GenerateSamples.py

**Comment by lanlan0924** [comment]
I'm very sorry. I read every line of code carefully last week and finally understood the meaning of your article. Thank you for providing open source code, which is very helpful to me.
If it's convenient, I'd like to ask you. If my image is RGB and the dimension is 256 * 256. Do I need to add some network layers?

I'm glad you can reply me in your busy schedule. I wish you a happy life and a smooth work!



| |
1729314-王岚
|
|
***@***.***
|
签名由网易邮箱大师定制
On 8/11/2022 ***@***.***> wrote：

If I was correct, they used SMOTE sampling when generating samples. Somewhat similar to SMOTE in hidden space. You can refer to G_SM function in GenerateSamples.py

**Comment by mnzhao** [comment]
I'm not the author... I think you might not need to add more layers for the CNN but maybe change the dimension of the hidden space?

**Comment by lanlan0924** [comment]
Oh, sorry ,I didn't read your ID carefully. 


Thank you for your proposal. I'll try it today!



| |
1729314-王岚
|
|
***@***.***
|
签名由网易邮箱大师定制
On 8/11/2022 ***@***.***> wrote：

I'm not the author... I think you might not need to add more layers for the CNN but maybe change the dimension of the hidden space?

**Comment by dd1github** [comment]
Hi, thank you both for your questions and comments.  As for the first issue, the SMOTE type sampling can be found in the generative file.  With regards to RGB, the architecture does require some changes to accomodate 3 channels instead of 1.  I have some sample code that you may be able to adopt for RGB and can email to you.

**Comment by lanlan0924** [comment]
I'm very sorry to question your code. Last week, I read your article and each line of code carefully again, and finally understood what you mean. Thank you for providing open source code, which is very helpful to me!

Thank you for sharing your code with me. If you have time, you can send it directly to my email.

I'm glad you can reply me in your busy schedule. I wish you a happy life and a smooth work!



| |
1729314-王岚
|
|
***@***.***
|
签名由网易邮箱大师定制
On 8/11/2022 ***@***.***> wrote：

Hi, thank you both for your questions and comments. As for the first issue, the SMOTE type sampling can be found in the generative file. With regards to RGB, the architecture does require some changes to accomodate 3 channels instead of 1. I have some sample code that you may be able to adopt for RGB and can email to you.
